# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.1
loader_version=0.18.5

# Mod Properties
mod_version=1.0.0
maven_group=dev.kishku.elytrahud3
archives_base_name=elytrahud3

# Dependencies
fabric_version=0.144.3+26.1
mod_menu_version=18.0.0-alpha.7
