license = "MIT"

[[mods]]
    modId = "elytrahud3"
    version = "${mod_version}"
    displayName = "ElytraHud3"
    authors = "Kishku7"
    description = '''Aviation-style flight HUD for Minecraft elytras. Do a Barrel Roll compatible.'''

[[dependencies.elytrahud3]]
    modId = "neoforge"
    type = "required"
    versionRange = "[26.1.2.30-beta,)"
    ordering = "NONE"
    side = "CLIENT"
[[dependencies.elytrahud3]]
    modId = "minecraft"
    type = "required"
    versionRange = "[26.1,)"
    ordering = "NONE"
    side = "CLIENT"
