modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/Kishku7/elytrahud3/issues"

[[mods]]
modId = "elytrahud3"
version = "${file.jarVersion}"
displayName = "ElytraHud3"
authors = "Kishku7"
description = '''Aviation-style flight HUD for Minecraft elytras. Do a Barrel Roll compatible.'''

[[dependencies.elytrahud3]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,21.2)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.elytrahud3]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.2)"
ordering = "NONE"
side = "CLIENT"
